export const ADD_FAVORITE_MOVIES = 'ADD_FAVORITE_MOVIES';
export const REMOVE_FAVORITE_MOVIES = 'REMOVE_FAVORITE_MOVIES';
export const SET_PAGE_NUMBERS = 'SET_PAGE_NUMBERS';
export const SET_CATEGORY_TYPES = 'SET_CATEGORY_TYPES';
export const SET_MOVIE_LIST = 'SET_MOVIE_LIST';
export const SET_RENDERED_LIST = 'SET_RENDERED_LIST';
export const SET_SEARCH_LIST = 'SET_SEARCH_LIST';
